print("Please enter the character for the eye")
eye = input()
print("Beep's expression is now as follows: {}.".format(eye))
print("     _______    ")
print("    / _   _ \   ")
print("  (|  "+ eye +"   "+ eye +"  |) ")
print("    \  ___  /   ")
print("     |_____|    ")
print("    /       \   ")
print("   /| @     |\  ")
print("  / |       | \ ")
print(" (_/ \_____/ \_)")
print("     (_____)    ")