print("This is how quadratic equation looks like")
print("a must not be equal to 0")
print("\t ax**2 + bx + c = 0")
print()
print("Lets calculate the value of x1 and x2")
print()
print("write value of a (with plus or minus)")
a = int(input())
print()
print("write value of b (with plus or minus)")
b = int(input())
print()
print("write value of c (with plus or minus)")
c = int(input())
print()
print("This is how YOUR quadratic equation looks like")
print("{}x**2 + {}x + {} = 0".format(a,b,c))
print()
d = (b*b -4*a*c)
print("the value of discriminant is: {}".format(d))
print()
import math
D = (math.sqrt(d))
print("the value of D is: {:.2f}".format(D))
print()
x1 = ((- b + D )/ a*2)
x2 = ((- b - D )/ a*2)
print("the value of x1 is: {:.2f}".format(x1))
print("the value of x2 is: {:.2f}".format(x2))